export const AUTH_LOGIN_REQUESTED = 'AUTH_LOGIN_REQUESTED'
export const AUTH_LOGIN_FAILURE   = 'AUTH_LOGIN_FAILURE'
export const AUTH_LOGIN_SUCCESS   = 'AUTH_LOGIN_SUCCESS'
export const AUTH_LOGIN_CLEAR     = 'AUTH_LOGIN_CLEAR'


